### ISSUE TITLE
Clozemaster Danish

### ISSUE THREAD

**Issue by Monikae** [ll-in-anki/Danish-8000-Sentences-Revamped#1]
I just have a question and found no other way of contacting you. I have been using your deck for some months and recently started Clozemaster. It has some of the same sentences including using Tom and Mary as the names all the time. Do you know why that is? Did the original deck borrow from Clozemaster or vice versa? Just curious.

**Comment by jeprecated** [comment]
No problem mate, question away here anytime.

The quick answer is that neither took from the other one, but that both took from https://tatoeba.org/eng/ which uses Tom and Mary very often in their examples. It says so [here in the about section of Clozemaster](https://www.clozemaster.com/about#where-are-the-sentences-from) and here's [a reddit thread with the creator of Clozemaster](https://www.reddit.com/r/clozemaster/comments/77vs33/how_are_the_clozemaster_sentences_getting_created/) saying as much 👍 

I hope you get some use out of the deck 👏 I have an update coming in a week or so that improves a few of the translations, but it's not major and doesn't affect too many (of the 8000+) cards 😅 

Fyi: I *highly* recommend pairing a beast of a deck like this with the Morphman add-on for Anki, if you are not already doing so. You know how there are maaany almost duplicate sentences in the deck such as `han faldt i søvn på hendes skulder` or `hun faldt i søvn på hans skulder` or `han faldt i søvn på min skulder` blahblahblah useless repetition? Well Morphman keep track of all notes that you know (that are learnt) and then keeps a list of all words that are in each of those note as your "known words", then orders the cards to bury all the cards with only words you already know (so no more useless repetition) and orders the rest to give you exactly 1 unknown word every new card 👍 

[Here is a very detailed guide](https://massimmersionapproach.com/table-of-contents/anki/morphman/) on how to set it up, with a video that explains it much better than I have, but I will happily share my own Danish setup for you if you like. 

Held og lykke!

**Comment by Monikae** [comment]
Thank you for your answer! Interesting!

And I have to look into Morphman.

Now that I have my Duolingo Danish tree completely on gold since yesterday I will spend more time with Anki and with Clozemaster.
